providers:
  openai:
    api_key: "your_openai_api_key"
    available_services:
      - transcription
      - translation
      - summarization
      - synthesis
  aws:
    access_key: "your_aws_access_key"
    secret_key: "your_aws_secret_key"
    region: "your_aws_region"
    available_services:
      - transcription
      - translation
      - synthesis
  gemini:
    api_key: "your_gemini_api_key"
    available_services:
      - translation
      - summarization
